/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Jeremy E. Grayson (https://sketchfab.com/JeremyGrayson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pizza-23ddac5a352e488da455da7e6f3c3cb5
Title: Pizza
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pizza(props) {
  const { nodes, materials } = useGLTF('/pizza.glb')
  return (
    <group {...props} scale={[1.5, 1.5, 1.5]} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 1.5, 0, 0]} castShadow={false} receiveShadow={false}  />
    </group>
  )
}

useGLTF.preload('/pizza.glb')
