import React, { useContext } from "react";
import { CartContext } from '@/components/CartContext';
import CartProduct from "../components/CartProduct";
import Head from "next/head";
import NavDev from "@/components/NavDev";
import Footer from "@/components/Footer";

export default function CartPage() {

    const cart = useContext(CartContext);

    const productsCount = cart.items.reduce((sum, product) => sum + product.quantity, 0);
  return (
    <>
    <Head>
        <title>Cart Page | Summary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href="/img/icon.png" />
      </Head>
      <NavDev/>
    <section id='cartpage' className='w-full h-full items-center mt-24'>
    <div className="relative pl-6 pr-6 ">
                  <p className="my-4 text-md md:text-xl leading-relaxed">
                    {productsCount > 0 ?
                        <>
                            <p className="text-gray-500">Pizza in your cart:</p>
                            {cart.items.map((currentProduct, idx) => (
                                  <CartProduct key={idx}
                                  name={currentProduct.name}  
                                  id={currentProduct.id} quantity={currentProduct.quantity}></CartProduct>
                            ))}
                            <h1 className="text-gray-500">Total Cost: {cart.getTotalCost().toFixed(2)}$</h1>
                        </>
                    :
                      <h1 className="text-red-500 text-center text-md md:text-2xl">There are no pizza in your cart!</h1>
                    }</p>
                </div>
                 <div className="text-center mb-5">
    <a href="https://buy.stripe.com/test_6oEaIz3M5fgqcZW3cc">
                <button  className=" bg-gray-500 hover:bg-red-500 text-white py-2 px-4 rounded-md mr-2">Order a tasty Pizza!</button></a>
                </div>   
    </section>
    <Footer/>
    </>
  )
}
