import NavDev from '@/components/NavDev'
import Head from 'next/head'
import React, { useContext, useState } from 'react'
import Link from 'next/link';
import Footer from '@/components/Footer';
import axios from 'axios';
import getStripe from '@/get-stripe';
import { CartContext } from '@/components/CartContext';


export default function Delivery() {

  const cart = useContext(CartContext);

  const redirectToCheckout = async () => {
    // Create Stripe checkout
    const {
      data: { id },
    } = await axios.post('/api/checkout_sessions', {
      items: Object.entries(cart.items).map(([_, { id, quantity }]) => ({
        price: id,
        quantity,
      })),
    });

    // Redirect to checkout
    const stripe = await getStripe();
    await stripe.redirectToCheckout({ sessionId: id });
  };

  return (
    <>
    <Head>
        <title>Delivery Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href="/img/icon.png" />
      </Head>
      <NavDev/>
    <section id='delivery' className='mt-12 pt-10  items-center justify-center mb-10 md:h-screen'>
    <div className="max-w-md mx-auto my-4 p-4 bg-red-500 rounded-md shadow-md">
      <h1 className="text-lg font-medium mb-4">Delivery Information</h1>
      <form>
        <div className="mb-4">
          <label htmlFor="firstName" className="block font-medium mb-1">
            First Name
          </label>
          <input
            type="text"
            id="firstName"
            name="firstName"
          
            required
            className="block w-full p-2 border rounded-md"
          />
        </div>
        <div className="mb-4">
          <label htmlFor="lastName" className="block font-medium mb-1">
            Last Name
          </label>
          <input
            type="text"
            id="lastName"
            name="lastName"
            
            required
            className="block w-full p-2 border rounded-md"
          />
        </div>
        <div className="mb-4">
          <label htmlFor="firstName" className="block font-medium mb-1">
            Phone Number
          </label>
          <input
            type="number"
            id="phoneNumber"
            name="phoneNumber"
            
            required
            className="block w-full p-2 border rounded-md"
          />
        </div>
        <div className="mb-4">
          <label htmlFor="address" className="block font-medium mb-1">
            Delivery Address
          </label>
          <input
            type='text'
            id="address"
            name="address"
            
            required
            className="block w-full p-2 border rounded-md"
          />
        </div>
        <div className="flex justify-end">
          <button
            type="submit" onClick={redirectToCheckout}
            className="bg-gray-500 text-white mr-5 py-2 px-4 rounded-md"
          >
            Pay
          </button>
          <Link href="/Summary">
            <p className="bg-gray-500 text-white py-2 px-4 rounded-md mr-2">
              Go to Summary
            </p>
          </Link>
        </div>
      </form>
    </div>
    </section>
    <Footer/>
    </>
  )
}