import About from '@/components/About';
import Contact from '@/components/Contact';
import Footer from '@/components/Footer';
import Main from '@/components/Main';
import Menu from '@/components/Menu';
import Navbar from '@/components/Nav';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { BarLoader } from 'react-spinners';

export default function Home() {

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // setLoading(true)
    setTimeout(() => {
      setLoading(false)
    }, 1000)    
  }, [])

  return (
    <>

      <Head>
        <title>Pizza Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href="/img/icon.png" />
      </Head>

    {
      loading ?

      <div
      className={`fixed top-0 left-0 w-full h-full flex justify-center items-center z-50 ${
        loading ? '' : 'hidden'
      }`}
    >
      <div className='absolute top-0 left-0 w-full h-full bg-white opacity-10' />
      <div className='w-1/3 flex flex-col items-center text-center'>
        <p className='text-slate-600 text-lg mb-4'>We are preparing pizza...</p>
        <div className='flex justify-center items-center'>
          <BarLoader color='red' loading={loading} size={30} />
        </div>
      </div>
    </div>

      :

      <main className="bg-red-500">
      <Navbar/>
      <Main/>
      <About/>
      <Menu/>
      <Contact/>
      <Footer/>
      </main>
    }
    </>
  );
};


